### ISSUE TITLE
Add convertPathData plugin

### ISSUE THREAD

**Issue by javierpose** [BohemianCoding/svgo-compressor#10]
I think that it is important to add convertPathData plugin in svgo.json by default. Without convertPathData this plugin is practically useless because It does not get hardly compression. convertPathData will compress a svg of 113kb to 69 kb. Most people will not change parameters in svgo.json.

**Comment by bomberstudios** [comment]
Hi @javierpose,

we've chosen the defaults for the plugin to achieve a balance between compression, code readability, and safety (some svgo plugins modify the visual output of the SVG file). We decided against enabling `convertDataPath` after running a few hundred tests with multiple SVGs, and finding out that the output for some of them was less than ideal (specifically when working with complex icons, since `convertDataPath` rounds some numbers and things can move around sometimes).

While we appreciate the feedback, calling the plugin "practically useless" seems a bit extreme.
