### ISSUE TITLE
Converting text to path

### ISSUE THREAD

**Issue by asinel** [BohemianCoding/svgo-compressor#28]
What about converting from `<text>` to `<path>`? It would be very useful for Android.

**Comment by bomberstudios** [comment]
That's a bit outside of the scope of this plugin, since it would require us to do the conversion on the rendering side, before the SVG is even generated.

There's no easy way of turning a `text` into a `path` reliably when you only have the SVG code; You'd also need the actual font files used, and a rendering system.

Sorry!
