### ISSUE TITLE
Not sure how to remove fill

### ISSUE THREAD

**Issue by dariusgarza** [BohemianCoding/svgo-compressor#35]
How do I get this feature to work? https://github.com/BohemianCoding/svgo-compressor#removeattrs

How to activate? I don't want fills in the svg. Thanks much.

**Comment by bomberstudios** [comment]
As explained in the docs, just do this:

- Click Plugins › SVGO Compressor › About SVGO Compressor
- Click 'Edit SVGO Settings…'
- At the end of your config, add this code

```
,
{
    "name": "removeAttrs",
    "params": {
        "attrs": "fill"
    }
}
```

so that it looks like this:

![screen shot 2018-08-10 at 09 56 09](https://user-images.githubusercontent.com/3832/43945830-b3dcd65c-9c83-11e8-9d22-518e4b6cdd86.png)

Save the file, and from now on your SVGs won't have a `fill` attribute.
