### ISSUE TITLE
Way to remove path and fill ids sketch generates?

### ISSUE THREAD

**Issue by amandablakley** [BohemianCoding/svgo-compressor#38]
So sketch adds a ton of nonsense ids to elements on export. I want items stored in groups to maintain the ID they are supplied with but every path is supplied an id as well named the fill number sketch has given it.

Is there a way to over ride this in SVGO's json file without Cleaning all IDs or using 
{
      "name": "removeAttrs",
      "params": {
        "attrs": "id"
      }
    }

Which I also tried and it also strips all ids obviously.

Ideally I am trying to find a way that our designers can export completely clean coded svgs from Sketch that would be viable for Devs not having to manually add custom IDs. But I am starting to think this may not be possible.

**Comment by bomberstudios** [comment]
I guess the easiest way to do that at the moment would be to write an SVGO plugin, or hack the source of the plugin to do what you need.

But this request made me wonder if it wouldn't be easier to support plugins for this plugin (what a tongue twister) so that you could easily add a `.js` file somewhere to transform your SVG output (which is basically what SVGO does)

**Comment by mathieudutour** [comment]
Version 1.6.0 allows to load a custom SVGO plugin by specifying a relative path: https://github.com/BohemianCoding/svgo-compressor#custom-svgo-plugins

It does require Sketch 52 tho.

Feel free to send a PR to add your svgo plugin to the list if you end up building it :)
