### ISSUE TITLE
Facing issue in extending svgo-compressor

### ISSUE THREAD

**Issue by zwattic** [BohemianCoding/svgo-compressor#48]
Hey, I wanted to export the compressed SVG as a JSX, I'm able to achieve this functionality through cli using [svg-to-jsx](https://www.npmjs.com/package/svg-to-jsx), but when I tried to import the svg-to-jsx module in the `/src/plugin.js` file, the following error is thrown -

<img width="869" alt="screenshot 2018-12-16 at 10 04 20 pm" src="https://user-images.githubusercontent.com/10823530/50268573-51a2da00-0451-11e9-8415-0b9fda9714e5.png">

`svg-to-jsx` follows commonJs pattern, so import should work just fine but it isn't in the case.

Can you please guide me if I'm doing something wrong?

**Comment by mathieudutour** [comment]
You are not doing anything wrong. It's because `svg-to-jsx` is depending on `xml2js` which uses a deprecated method (`require('events').EventEmitter` while it should just be `require('events')`).

The plugin is not running in Node so the `events` module is actually a polyfill that I wrote: https://github.com/skpm/events and I didn't polyfill the deprecated methods. Maybe I should.

**Comment by zwattic** [comment]
Thank you! As you mentioned, updating the `events.EventEmitter` to `events` in the `xml2js/parser.js` worked.
I'm still wrapping my head around the Node's event API, if it works out I can give polyfilling a go.
