### ISSUE TITLE
Not working Sketch 64>

### ISSUE THREAD

**Issue by mLihs** [BohemianCoding/svgo-compressor#67]
Hi seams the SVGO Compressor is not working correctly. The decimal settings have no affect to the output.

**Comment by bomberstudios** [comment]
I assume you mean the `floatPrecision` attribute in `svgo.json`?

Just tested it and works as expected. That setting controls the maximum number of decimal positions for attributes _that are not path definitions_ (for obvious reasons, since that would distort the paths).

Here's a partial example of an export.

With the plugin disabled:

```
<radialGradient cx="50%" cy="168.359375%" fx="50%" fy="168.359375%" r="3186.97791%" gradientTransform="translate(0.500000,1.683594),scale(0.016129,1.000000),rotate(180.000000),translate(-0.500000,-1.683594)" id="radialGradient-1">
```

Plugin enabled, `floatPrecision` set to `3` (the default value). See how the attributes are rounded to 3 decimals:

```
<radialGradient id="cloud-a" cx="50%" cy="168.359%" r="3186.978%" fx="50%" fy="168.359%" gradientTransform="matrix(-.01613 0 0 -1 .508 3.367)">
```

Plugin enabled, `floatPrecision` set to `1`:

```
<radialGradient id="cloud-a" cx="50%" cy="168.4%" r="3187%" fx="50%" fy="168.4%" gradientTransform="matrix(-.01613 0 0 -1 .5 3.4)">
```

Feel free to reopen if this is not what you're seeing.
