### ISSUE TITLE
Edit SVGO Settings is missing

### ISSUE THREAD

**Issue by maggeei** [BohemianCoding/svgo-compressor#83]
Since the update to 2.0.0, it's not possible anymore to change the edit the SVG settings is missing. This is vital to our team, so it's a pity that it's gone. As it's still written in the plugin description on the [sketch page](https://www.sketch.com/extensions/plugins/svgo-compressor/).

**Comment by fireinureeyes** [comment]
Same for us, using the standard settings is not an option due to different requirements from our devs.

**Comment by bomberstudios** [comment]
Hi there!

Apologies for the disruption in your workflows.

Custom configurations for the SVGO backend complicated the plugin code enormously (which in turn made it really hard for us to troubleshoot issues). We made the decision to remove that feature to make things more robust for the majority of our customers.

However, since we’ve upgraded `svgo` to 2.6.0, we now use a configuration system that closely matches [the way you do things when using SVGO directly](https://github.com/svg/svgo#configuration).

You can see what it looks like here: https://github.com/sketch-hq/svgo-compressor/blob/develop/src/plugin.js#L30-L53

I will update the documentation here and on the site to better reflect this change, and explain how you can use custom configurations. If you need immediate help with this, I’m happy to discuss things directly over email (ping me at ale@sketch.com).

**Comment by fireinureeyes** [comment]
Hi @bomberstudios , 

thanks for your reply! 

Looking forward to reading the custom configurations documentation, although we will probably stick to the working [1.7.0](https://github.com/sketch-hq/svgo-compressor/releases/tag/v1.7.0) for economical reasons for now.

**Comment by jl-stellar** [comment]
+1 for this, we're in the same situation as @fireinureeyes

**Comment by peeke** [comment]
Big issue for us as well. With the default settings SVGO doesn't prefix id attributes, leading to conflicts when using them in our websites.

**Comment by bomberstudios** [comment]
Version 2.1.0 of the plugin, just released, supports custom configurations. See the docs at https://github.com/sketch-hq/svgo-compressor#custom-svgo-configuration and let me know how that works for you.

I’m closing this issue, but feel free to open new ones for comments / suggestions / bug reports
